name: effecient

description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    


 
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.3 # Check for the latest version
  location: ^5.0.3
  geolocator: ^7.6.2
  geocoding: ^2.1.0
  flogger: ^0.0.8
  # Fire base dependenies for Real Time DB integration
  firebase_core: ^2.7.1
  firebase_core_web: ^2.10.0
  firebase_database: ^10.4.0
  firebase_auth: ^4.17.3
  google_sign_in: ^6.2.1
  syncfusion_flutter_maps: ^24.1.46
  flutter_svg: ^2.0.9
  flutter_polyline_points: ^2.0.0
  
  http: ^1.2.0
  google_nav_bar: ^5.0.6
  firebase_storage: ^11.6.5
  image_picker: ^1.0.7
  cloud_firestore: ^4.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

 
